In [22]:
import pandas as pd
import os
import pinecone
from dotenv import load_dotenv
from pinecone import Pinecone, ServerlessSpec
from sentence_transformers import SentenceTransformer

load_dotenv()

True

In [5]:
files = pd.read_csv("course_descriptions.csv", encoding="cp1252")

In [6]:
files.head()

,course_name,course_slug,course_technology,course_description,course_topic,course_description_short
0,Introduction to Tableau,tableau,tableau,Tableau is now one of the most popular busines...,data visualization,Teaching you how to tell compelling stories wi...
1,The Complete Data Visualization Course with Py...,data-visualization,python,The Data Visualization course is designed for ...,data visualization,Teaching you how to master the art of creating...
2,Introduction to R Programming,introduction-to-r-programming,r,R is one of the best programming languages spe...,programming,"Providing you with the skills to manipulate, a..."
3,Data Preprocessing with NumPy,data-preprocessing-numpy,python,This course is designed to show you how to wor...,data processing,This course will guide you through one of Pyth...
4,Introduction to Data and Data Science,intro-to-data-and-data-science,theory,Working with data is an essential part of main...,machine learning,Introducing you to the field of data science a...

In [9]:
def create_course_description(row):
    return f"""The course name is {row["course_name"]}, the slug is {row["course_slug"]}, the technologu is {row["course_technology"]}, and the topic is {row["course_topic"]}."""

In [10]:
files["course_description_new"] = files.apply(create_course_description, axis=1)
files.head()

,course_name,course_slug,course_technology,course_description,course_topic,course_description_short,course_description_new
0,Introduction to Tableau,tableau,tableau,Tableau is now one of the most popular busines...,data visualization,Teaching you how to tell compelling stories wi...,"The course name is Introduction to Tableau, th..."
1,The Complete Data Visualization Course with Py...,data-visualization,python,The Data Visualization course is designed for ...,data visualization,Teaching you how to master the art of creating...,The course name is The Complete Data Visualiza...
2,Introduction to R Programming,introduction-to-r-programming,r,R is one of the best programming languages spe...,programming,"Providing you with the skills to manipulate, a...",The course name is Introduction to R Programmi...
3,Data Preprocessing with NumPy,data-preprocessing-numpy,python,This course is designed to show you how to wor...,data processing,This course will guide you through one of Pyth...,The course name is Data Preprocessing with Num...
4,Introduction to Data and Data Science,intro-to-data-and-data-science,theory,Working with data is an essential part of main...,machine learning,Introducing you to the field of data science a...,The course name is Introduction to Data and Da...

In [15]:
pc = Pinecone(
    api_key=os.getenv("PINECONE_API_KEY"), environment=os.getenv("PINECONE_ENVIRONMENT")
)

In [17]:
index_name = "my-index"
dimensions = 384
metric = "cosine"

In [18]:
if index_name in [index.name for index in pc.list_indexes()]:
    print(f"Index '{index_name}' already exists.")
    pc.delete_index(index_name)
    print(f"Index '{index_name}' deleted.")
else:
    print(f"Index '{index_name}' does not exist.")

Index 'my-index' does not exist.

In [20]:
pc.create_index(
    name=index_name,
    dimension=dimensions,
    metric=metric,
    spec=ServerlessSpec(cloud="aws", region="us-east-1"),
)

{
    "name": "my-index",
    "metric": "cosine",
    "host": "my-index-h2xw5gc.svc.aped-4627-b74a.pinecone.io",
    "spec": {
        "serverless": {
            "region": "us-east-1",
            "cloud": "aws",
            "read_capacity": {
                "mode": "OnDemand",
                "status": {
                    "state": "Ready",
                    "current_shards": null,
                    "current_replicas": null
                }
            }
        }
    },
    "status": {
        "ready": true,
        "state": "Ready"
    },
    "vector_type": "dense",
    "dimension": 384,
    "deletion_protection": "disabled",
    "tags": null,
    "_response_info": {
        "raw_headers": {
            "content-type": "application/json",
            "access-control-allow-origin": "*",
            "vary": "origin,access-control-request-method,access-control-request-headers",
            "access-control-expose-headers": "*",
            "x-pinecone-api-version": "2025-10",
            "x-cloud-trace-context": "8e41b641ba7358a6310831aa0423756e",
            "date": "Sun, 04 Jan 2026 07:44:17 GMT",
            "server": "Google Frontend",
            "content-length": "385",
            "via": "1.1 google",
            "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
        }
    }
}

In [21]:
index = pc.Index(index_name)

/opt/anaconda3/envs/langchain_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Embedding the data

In [23]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [24]:
def create_embeddings(row):
    combined_text = " ".join(
        [
            str(row[field])
            for field in [
                "course_description",
                "course_description_new",
                "course_description_short",
            ]
        ]
    )
    embedding = model.encode(combined_text, show_progress_bar=False).tolist()
    return embedding

In [25]:
files["embeddings"] = files.apply(create_embeddings, axis=1)

In [27]:
vectors_to_upsert = [
    (str(row["course_name"]), row["embeddings"]) for _, row in files.iterrows()
]

index.upsert(vectors=vectors_to_upsert)

print("Vectors upserted successfully.")

Vectors upserted successfully.

In [28]:
files.head()

,course_name,course_slug,course_technology,course_description,course_topic,course_description_short,course_description_new,embeddings
0,Introduction to Tableau,tableau,tableau,Tableau is now one of the most popular busines...,data visualization,Teaching you how to tell compelling stories wi...,"The course name is Introduction to Tableau, th...","[0.04754232242703438, -0.025731457397341728, -..."
1,The Complete Data Visualization Course with Py...,data-visualization,python,The Data Visualization course is designed for ...,data visualization,Teaching you how to master the art of creating...,The course name is The Complete Data Visualiza...,"[0.045970506966114044, -0.0190302524715662, -0..."
2,Introduction to R Programming,introduction-to-r-programming,r,R is one of the best programming languages spe...,programming,"Providing you with the skills to manipulate, a...",The course name is Introduction to R Programmi...,"[-0.032060395926237106, 0.003249592613428831, ..."
3,Data Preprocessing with NumPy,data-preprocessing-numpy,python,This course is designed to show you how to wor...,data processing,This course will guide you through one of Pyth...,The course name is Data Preprocessing with Num...,"[-0.042630571871995926, -0.011502289213240147,..."
4,Introduction to Data and Data Science,intro-to-data-and-data-science,theory,Working with data is an essential part of main...,machine learning,Introducing you to the field of data science a...,The course name is Introduction to Data and Da...,"[0.003696816274896264, 0.013247908093035221, -..."

### Semantic search

In [30]:
query = "clustering"
query_embedding = model.encode(query).tolist()

In [31]:
query_results = index.query(
    vector=[query_embedding], top_k=12, include_metadata=True, include_values=True
)

In [32]:
query_results

QueryResponse(matches=[{'id': 'Machine Learning in Excel',
 'score': 0.358200073,
 'values': [0.0033723868,
            -0.0292600784,
            -0.0221662056,
            -0.0199606232,
            -0.0260353759,
            -0.0285246894,
            -0.0483845398,
            -0.0468946844,
            0.00338905421,
            0.0334535874,
            -0.0416799746,
            -0.0374811329,
            0.0728667751,
            -0.0349725336,
            0.00254065124,
            0.0390005931,
            -0.00747278472,
            -0.00826809,
            0.000724587124,
            -0.0621499643,
            0.0899556577,
            0.0292359237,
            -0.046205081,
            -0.0267778076,
            0.0370306559,
            0.0199046358,
            0.0608185865,
            -0.0015481452,
            -0.0428084768,
            -0.0307227261,
            -0.0565921925,
            0.0206759945,
            0.00639701681,
            0.0444554053,
            -0.0655426234,
            -0.0320837833,
            -0.0135992849,
            -0.00422148919,
            0.0268985387,
            0.0493377782,
            -0.0457623638,
            0.0181360524,
            0.0336384214,
            -0.060687311,
            0.0769208819,
            0.0382292122,
            -0.0839789435,
            -0.0636165217,
            0.0222236346,
            0.0367836095,
            -0.0975156203,
            -0.0895581245,
            0.00871003233,
            -0.00758162281,
            -0.0496049412,
            -0.0459496826,
            0.0614972264,
            0.012143394,
            0.088658981,
            -0.0924952626,
            0.0642527789,
            -0.0753748864,
            -0.0165399387,
            0.0271396376,
            -0.00603249576,
            -0.0136557342,
            -0.0506143272,
            0.110767782,
            0.0238528103,
            -0.059405148,
            -0.0652838051,
            0.0376892723,
            -0.050413508,
            0.0251696743,
            0.0207505487,
            0.00735059706,
            -0.00904247444,
            -0.0158145558,
            0.0154294362,
            0.0366823599,
            -0.0121614141,
            0.0621328242,
            -0.0294933226,
            0.0599499196,
            0.00978607684,
            -0.059940882,
            -0.023184076,
            0.078363888,
            -0.0107389223,
            -0.00773959327,
            0.0348869711,
            0.00213121064,
            0.0178514216,
            0.0304508787,
            -0.0892581269,
            -0.0310952179,
            -0.0402971171,
            -0.0454295203,
            0.0698221475,
            -0.0053471541,
            -0.0808131,
            0.00259700324,
            0.0135900509,
            -0.0404666699,
            -0.0205053929,
            -0.0342401229,
            0.0547749698,
            -0.00840737112,
            0.116368085,
            -0.05008379,
            0.0149422847,
            -0.0288834814,
            -0.108521357,
            -0.0521566384,
            -0.0120701939,
            0.0409019627,
            0.0801480711,
            -0.0603043251,
            -0.00758468825,
            0.0552905202,
            -0.0260966066,
            -0.0209795777,
            0.0150874732,
            -0.0330136754,
            0.0771468803,
            -0.0739807189,
            -0.108728193,
            -9.78380203e-34,
            -0.0371639319,
            -0.0263546444,
            -0.0193511248,
            0.0236326829,
            0.100944,
            -0.0619013719,
            0.0155760627,
            -0.00559071172,
            0.0176220909,
            0.0033892917,
            -0.0325230546,
            0.123772301,
            -0.0169972833,
            0.103643171,
            0.0438282862,
            -0.0082660364,
            0.056167502,
            -0.00998120476,
            -0.0319033638,
            0.0418795981,
            0.0335182771,
            -0.040162418,
            0.0242020357,
            -0.0161937214,
            -0.0372427925,
            0.0665671453,
            0.10307128,
            -0.00564745441,
            0.105789699,
            0.0173843186,
            0.0108907344,
            0.0461621955,
            -0.151648775,
            -0.0187574308,
            0.096690625,
            0.0671101958,
            -0.0679934546,
            0.00963438209,
            0.0445377454,
            0.0234403815,
            -0.0448608175,
            -0.00808208436,
            0.0685816,
            -0.0762557089,
            -0.0304559767,
            0.0528893918,
            0.0279139224,
            0.0349532589,
            0.106061481,
            -0.0360878631,
            -0.0753918961,
            -0.0726823,
            0.00741098821,
            0.00590109127,
            -0.0646179244,
            0.129652798,
            0.00521208672,
            -0.0300340354,
            -0.0535401739,
            0.0484709032,
            -0.00871108286,
            -0.0103828339,
            0.0345695503,
            -0.0114152543,
            -0.0917154476,
            -0.0389719792,
            0.0462178402,
            0.00684569,
            0.0785854757,
            -0.0104036126,
            -0.0458054356,
            -0.0250897445,
            0.0838497505,
            -0.0352002122,
            0.0298294239,
            0.0763586685,
            0.0246939436,
            0.000581216242,
            -0.054380659,
            -0.0292951912,
            -0.0398441441,
            -0.0356403925,
            -0.0222304817,
            -0.0750091374,
            -0.0270981733,
            0.0188091453,
            0.0106023857,
            -0.0167924669,
            -0.072920531,
            -0.00300483429,
            -0.0783176646,
            0.079995662,
            -0.0151417973,
            0.0928426608,
            -0.0153089287,
            -2.80529357e-33,
            0.0123563083,
            0.0811038166,
            -0.052804593,
            0.0344239436,
            0.0831898898,
            0.0581495278,
            -0.0703209713,
            0.0153534301,
            0.00936358608,
            -0.035635639,
            -0.0170021169,
            -0.0165917296,
            0.0375148505,
            0.1449655,
            -0.00394277601,
            0.042784255,
            -0.0189200751,
            -0.0505198538,
            -0.088518478,
            -0.0848550871,
            -0.0685996637,
            0.0205428172,
            -0.0433186963,
            -0.0843894184,
            0.0314791352,
            -0.00159589353,
            -0.0813255161,
            0.00374408858,
            -0.0313246101,
            0.03255447,
            -0.049911771,
            0.000308191549,
            -0.0374489,
            0.0125654237,
            0.0127837975,
            0.0164761264,
            0.00921282917,
            -0.0404823944,
            0.0656535104,
            0.0287876055,
            0.0764435902,
            -0.016843332,
            -0.0112733906,
            -0.0928816497,
            0.0184831731,
            -0.0448207781,
            0.0299425833,
            -0.00641216896,
            0.0938986316,
            -0.0383985192,
            -0.0231391415,
            0.0895516276,
            0.0223970804,
            0.0116418572,
            0.0160383973,
            0.0696948171,
            -0.00670432113,
            -0.0348775424,
            -0.00365865091,
            -0.0340839736,
            -0.125266939,
            -0.0653837547,
            0.0772931054,
            0.0596989803,
            -0.0421873331,
            -0.0104818325,
            0.00711703533,
            -0.0381250605,
            -0.0213368796,
            0.000157463117,
            -0.0518009327,
            0.0888594911,
            0.0246379171,
            0.0119247222,
            -0.0649071783,
            -0.0866971686,
            -0.0824236274,
            -0.087004751,
            -0.0890266672,
            -0.00706782,
            0.0716812685,
            -0.0169156957,
            -0.0842759,
            0.0890200287,
            0.0493232533,
            0.0431651808,
            0.0987322852,
            -0.0163935944,
            -0.0379154943,
            -0.0239059348,
            -0.0741226822,
            0.06840121,
            -0.0282449685,
            0.0137977544,
            -0.103051662,
            -3.44187434e-08,
            -0.0577347204,
            -0.00845969934,
            0.0226398576,
            -0.0100720646,
            0.067080386,
            0.051052209,
            -0.0689069107,
            0.115175247,
            -0.049014207,
            0.0853188485,
            0.000811971317,
            -0.0150846839,
            -0.0138242478,
            0.0517712869,
            -0.00667285407,
            0.0293533765,
            0.0304038357,
            0.0097715091,
            -0.000141402561,
            -0.0201416817,
            0.0294604134,
            -0.055177357,
            -0.0250327662,
            0.0585667863,
            0.0581817552,
            -0.118500687,
            0.00858715083,
            0.0224502869,
            0.0137696117,
            0.0244346038,
            -0.0404092856,
            0.0568569973,
            0.0334043689,
            -0.0679766834,
            -0.00413350808,
            0.0426522121,
            0.0612228848,
            -0.0518921651,
            0.0485266931,
            0.0243148357,
            -0.0343212821,
            0.0129263243,
            -0.0305547193,
            -0.00431838213,
            0.0300273318,
            0.0276131332,
            0.0696445,
            -0.0443455912,
            -0.0154310632,
            0.0489794351,
            0.0259956326,
            0.0154158035,
            -0.022736365,
            0.0676080585,
            0.00396650238,
            0.0690884069,
            -0.0494688898,
            -0.0928323343,
            0.088216871,
            0.0207530838,
            0.0335376337,
            0.00162123144,
            -0.0230799168,
            -0.0076796487]}, {'id': 'Machine Learning with K-Nearest Neighbors',
 'score': 0.340294361,
 'values': [-0.082061477,
            -0.0852524787,
            0.0219324101,
            -0.0600850508,
            -0.00815406069,
            -0.0475116596,
            -0.0156675316,
            -0.0719991252,
            -0.084816508,
            -0.0213365052,
            -0.0728840083,
            0.0258422345,
            0.086407952,
            -0.0212047342,
            -0.0538456142,
            -0.0162231587,
            0.0240204185,
            0.0328567028,
            -0.0318664834,
            -0.0776802599,
            0.0506963283,
            0.00786418747,
            0.0181629285,
            -0.0111125009,
            0.00884494372,
            0.0130005302,
            0.144005507,
            0.042350851,
            -0.0347511582,
            -0.00657082535,
            -0.0319074877,
            -0.00376224774,
            -0.0184677299,
            -0.0315414034,
            -0.0748230219,
            0.00144125184,
            -0.0376166776,
            0.0405858569,
            -0.0178413875,
            0.0609004907,
            -0.0133782867,
            -0.0754967108,
            0.0138345584,
            -0.0420168191,
            0.104847006,
            0.0908044055,
            -0.0578126,
            -0.0429156162,
            0.0168414582,
            0.00947941095,
            -0.0740415,
            -0.0701770186,
            -0.0453138947,
            0.0116340518,
            -0.019686792,
            -0.00690755481,
            0.0205059033,
            -0.0183025822,
            0.0169647876,
            -0.0305012576,
            0.0921464637,
            -0.0653025,
            -0.0461776666,
            -0.00978905242,
            0.0374230742,
            -0.0359408818,
            0.0180084817,
            0.0869564414,
            0.0149480319,
            -0.072510913,
            0.0227845255,
            0.0352669619,
            -0.0262690298,
            0.0908669606,
            0.0299450178,
            -0.0236064345,
            0.0786428,
            0.0295275152,
            -0.0152819715,
            -0.00676672533,
            0.0146260085,
            0.0547430255,
            -0.0086359717,
            0.0167375542,
            0.0159291122,
            -0.0758454129,
            -0.0140558174,
            0.0646886677,
            -0.0433656611,
            -0.0106437933,
            0.0574973449,
            -0.0306115374,
            -0.00343909441,
            -0.0826535746,
            0.044614464,
            0.0405303165,
            -0.00710219,
            -0.0493627861,
            0.00253765844,
            0.0507056713,
            -0.0310401656,
            0.0121301375,
            -0.0419644788,
            -0.0459755,
            0.0717933625,
            0.0623855889,
            0.049688518,
            -0.00583443465,
            0.107698031,
            -0.0659070164,
            -0.00196982455,
            -0.0225399788,
            -0.121987574,
            0.000510299229,
            0.0316837355,
            -0.0191449653,
            0.0356771462,
            -0.00212850142,
            -0.023055708,
            0.0614172965,
            -0.0876716152,
            -0.00190679706,
            -0.0418509394,
            0.0300681517,
            0.102653906,
            0.0621254481,
            -0.0841777921,
            8.80600379e-34,
            -0.000915396609,
            0.0243479125,
            0.00508849137,
            -0.0445572,
            0.0386219919,
            -0.112130024,
            -0.0109195458,
            0.0201124195,
            0.016469555,
            0.0398839265,
            0.00222798693,
            0.0572602078,
            0.0178296641,
            -0.00721692666,
            0.00990800373,
            -0.0597427748,
            0.0421416685,
            -0.0283823889,
            -0.0037615269,
            0.0625152737,
            0.0245458186,
            -0.0300056022,
            0.0402948558,
            -0.00148570735,
            -0.0183775853,
            0.0137260091,
            0.0205600541,
            -0.0552410185,
            0.0664163083,
            0.00845412,
            0.0450978465,
            0.0206419807,
            -0.0799774677,
            -0.00488165347,
            -0.00640807487,
            -0.0197342,
            -0.0315889306,
            -0.0405656,
            0.0272865798,
            -0.0390499495,
            -0.0494471863,
            -0.00831032079,
            0.00641028583,
            -0.060442239,
            -0.0122430101,
            0.0811123475,
            0.0140954191,
            -0.00189659745,
            0.0400105044,
            -0.0224134885,
            -0.0379677489,
            -0.0990374684,
            -0.0336987674,
            0.0293352157,
            -0.0435593911,
            0.104566753,
            0.0583486333,
            -0.0970783606,
            -0.00318051828,
            0.0136785246,
            0.0450804308,
            0.0020744144,
            0.0746496394,
            -0.00604227278,
            -0.0268190335,
            -0.0394820124,
            0.0269866809,
            0.00518284366,
            0.0808058158,
            -0.000706318242,
            -0.0528357178,
            0.0395881534,
            0.0230477583,
            0.0230447818,
            0.0785950497,
            0.0635101199,
            0.018873712,
            -0.0584770814,
            -0.0471379459,
            0.0266676564,
            -0.0031132116,
            0.0373312868,
            -0.0154723367,
            -0.0936555341,
            -0.026111031,
            0.0161355026,
            -0.0403056033,
            -0.0630259737,
            -0.0693536922,
            -0.00897371676,
            -0.0441040322,
            0.0237340778,
            -0.0763764381,
            0.0569589138,
            -0.0347231403,
            -2.52969341e-33,
            0.00232370594,
            0.0988907516,
            0.0185741447,
            0.0830094218,
            0.0303669,
            0.0405674055,
            -0.0725692958,
            -0.0033325993,
            -0.0132654263,
            -0.015480007,
            -0.0782694072,
            -0.00489602424,
            0.0879426897,
            0.0392570384,
            0.0343444124,
            0.044881586,
            -0.0603403673,
            -0.0511697195,
            -0.0142762819,
            0.0252550989,
            -0.0999947861,
            0.0447455533,
            -0.08186768,
            -0.068864353,
            -0.037151929,
            -0.0130753154,
            0.0050342693,
            0.053625863,
            -0.043701414,
            -0.0108518898,
            -0.0227894131,
            -0.0210853051,
            -0.0207453016,
            -0.0459131971,
            0.0239949506,
            0.0472142473,
            0.0238666181,
            -0.0785866454,
            0.0233383644,
            0.0190526806,
            0.0884912461,
            0.0357191972,
            -0.0148622086,
            -0.0660075098,
            -0.0402646437,
            -0.076156348,
            -0.0491741,
            0.0846572518,
            0.047137253,
            -0.0349901281,
            0.0906297192,
            0.0493774861,
            -0.0200120285,
            0.0234736912,
            0.0143706985,
            0.100364082,
            -0.0290993713,
            0.0614131726,
            0.0472655855,
            0.0675815344,
            -0.0707705393,
            -0.121484533,
            0.0443373397,
            0.12091653,
            -0.090756461,
            -0.0295327697,
            -0.0193375591,
            0.102355517,
            -0.0128810043,
            -0.000397557771,
            -0.0815939829,
            0.113556139,
            0.0664955825,
            0.0117633687,
            -0.0863701776,
            -0.0860252157,
            0.00883690827,
            -0.020057993,
            -0.0444450341,
            0.0386271924,
            0.0419986881,
            -0.0365583859,
            -0.0603585616,
            0.0819487944,
            0.0327563249,
            0.11291521,
            0.188020706,
            -0.0142567782,
            0.0237295423,
            -0.106140263,
            -0.0424278863,
            0.0814747,
            -0.0568968914,
            -0.0216572862,
            -0.0533859842,
            -4.5557158e-08,
            -0.0236401781,
            -0.0366741456,
            0.0823328644,
            3.64557127e-05,
            0.0489365533,
            0.0556239076,
            0.00512513565,
            0.0635401458,
            -0.121298164,
            -0.00219004601,
            0.0305921771,
            -0.026868267,
            -0.0661241785,
            0.0482778139,
            -0.00530713331,
            0.0445769951,
            0.0387410671,
            0.0232045799,
            -0.0245875753,
            0.0613862053,
            0.055116687,
            -0.0101886969,
            0.0367139801,
            0.0373748653,
            0.0450056978,
            -0.0816855058,
            0.0219068248,
            -0.00920888782,
            0.0532257,
            0.0313807428,
            -0.067259647,
            -0.00581482938,
            0.0206698608,
            -0.0609793514,
            0.0603925213,
            0.0641083643,
            -0.0108881388,
            -0.0374792032,
            0.0286989324,
            0.00750249438,
            -0.0507864952,
            -0.0107218586,
            -0.0440470576,
            -0.000268224016,
            0.0228634272,
            0.0411687344,

In [33]:
for match in query_results.matches:
    print(f"Course Name: {match.id}, Score: {match.score}")

Course Name: Machine Learning in Excel, Score: 0.358200073
Course Name: Machine Learning with K-Nearest Neighbors, Score: 0.340294361
Course Name: Customer Churn Analysis with SQL and Tableau, Score: 0.297932625
Course Name: Linear Algebra and Feature Selection, Score: 0.271223098
Course Name: Machine Learning in Python, Score: 0.265728
Course Name: Growth Analysis with SQL, Python, and Tableau  , Score: 0.260608673
Course Name: Fashion Analytics with Tableau, Score: 0.25161314
Course Name: Customer Engagement Analysis with SQL and Tableau, Score: 0.240436569
Course Name: Machine Learning with Naive Bayes, Score: 0.237494484
Course Name: Data Analysis with Excel Pivot Tables, Score: 0.233613014
Course Name: Data Preprocessing with NumPy, Score: 0.227066055
Course Name: Machine Learning with Support Vector Machines, Score: 0.226127625